apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: t1-ajq
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Welcome to Nginx</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          text-align: center;
          background-color: #f4f4f4;
          margin: 0;
          padding: 0;
        }
        header {
          background-color: #0078d7;
          color: white;
          padding: 20px;
        }
        main {
          padding: 20px;
        }
        a {
          color: #0078d7;
          text-decoration: none;
        }
        a:hover {
          text-decoration: underline;
        }
      </style>
    </head>
    <body>
      <header>
        <h1>Welcome to My Nginx Server</h1>
      </header>
      <main>
        <p>Adrian Quiambao was here!</p>
        <p>You may visit my GitHub at <a href="https://github.com/justadevopsguy" target="_blank">https://github.com/justadevopsguy</a></p>
        <p>Or visit my blog at <a href="https://ajquiambao.com/" target="_blank">https://ajquiambao.com/</a></p>
      </main>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: t1-ajq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-index-vol
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: nginx-index-vol
          configMap:
            name: nginx-index
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: t1-ajq
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "80"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "30"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
